x-signoz-common: &signoz-common
  networks:
    - signoz-net
  logging:
    options:
      max-size: 50m
      max-file: "3"
  restart: unless-stopped

x-signoz-clickhouse-defaults: &signoz-clickhouse-defaults
  !!merge <<: *signoz-common
  image: clickhouse/clickhouse-server:25.5.6
  tty: true
  labels:
    signoz.io/scrape: "true"
    signoz.io/port: "9363"
    signoz.io/path: "/metrics"
  depends_on:
    signoz-init-clickhouse:
      condition: service_completed_successfully
    signoz-zookeeper:
      condition: service_healthy
  healthcheck:
    test:
      - CMD
      - wget
      - --spider
      - -q
      - 0.0.0.0:8123/ping
    interval: 30s
    timeout: 5s
    retries: 3
  ulimits:
    nproc: 65535
    nofile:
      soft: 262144
      hard: 262144
  environment:
    - CLICKHOUSE_SKIP_USER_SETUP=1

x-signoz-zookeeper-defaults: &signoz-zookeeper-defaults
  !!merge <<: *signoz-common
  image: signoz/zookeeper:3.7.1
  user: root
  labels:
    signoz.io/scrape: "true"
    signoz.io/port: "9141"
    signoz.io/path: "/metrics"
  healthcheck:
    test:
      - CMD-SHELL
      - curl -s -m 2 http://localhost:8080/commands/ruok | grep error | grep null
    interval: 30s
    timeout: 5s
    retries: 3

x-signoz-db-depend: &signoz-db-depend
  !!merge <<: *signoz-common
  depends_on:
    signoz-clickhouse:
      condition: service_healthy
    signoz-schema-migrator-sync:
      condition: service_completed_successfully

services:
  # Nango
  nango-server:
    profiles: [ "nango" ]
    image: nangohq/nango-server:hosted-0.68.0
    container_name: nango-server
    platform: linux/amd64
    environment:
      - NANGO_ENCRYPTION_KEY
      - NANGO_DASHBOARD_USERNAME=
      - NANGO_DASHBOARD_PASSWORD=
      - NANGO_DB_USER=${NANGO_DB_USER:-nango}
      - NANGO_DB_PASSWORD=${NANGO_DB_PASSWORD:-nango}
      - NANGO_DB_HOST=${NANGO_DB_HOST:-nango-db}
      - NANGO_DB_NAME=${NANGO_DB_NAME:-nango}
      - RECORDS_DATABASE_URL=postgresql://${NANGO_DB_USER:-nango}:${NANGO_DB_PASSWORD:-nango}@${NANGO_DB_HOST:-nango-db}:5432/${NANGO_DB_NAME:-nango}
      - NANGO_SERVER_URL=${NANGO_SERVER_URL:-http://localhost:3003}
      - NANGO_PUBLIC_SERVER_URL=${NANGO_PUBLIC_SERVER_URL:-http://localhost:3003}
      - SERVER_PORT=${NANGO_SERVER_PORT:-3003}
      - FLAG_SERVE_CONNECT_UI=${NANGO_FLAG_SERVE_CONNECT_UI:-true}
      - NANGO_CONNECT_UI_PORT=${NANGO_CONNECT_UI_PORT:-3009}
      - FLAG_AUTH_ENABLED=${NANGO_FLAG_AUTH_ENABLED:-false}
      - LOG_LEVEL=${NANGO_LOG_LEVEL:-info}
      - CSP_REPORT_ONLY=true
    volumes:
      - './nango/providers.yaml:/app/nango/packages/providers/providers.yaml'
    ports:
      - '3050:${NANGO_SERVER_PORT:-3003}'
      - '3051:${NANGO_CONNECT_UI_PORT:-3009}'
    networks:
      - nango-net
    depends_on:
      - nango-db
      - nango-redis
    restart: unless-stopped

  nango-db:
    profiles: [ "nango" ]
    image: postgres:16.0-alpine
    container_name: nango-db
    environment:
      POSTGRES_PASSWORD: ${NANGO_DB_PASSWORD:-nango}
      POSTGRES_USER: ${NANGO_DB_USER:-nango}
      POSTGRES_DB: ${NANGO_DB_NAME:-nango}
    volumes:
      - nango-db:/var/lib/postgresql/data
    networks:
      - nango-net
    restart: unless-stopped

  nango-redis:
    profiles: [ "nango" ]
    image: redis:7.2.4
    container_name: nango-redis
    networks:
      - nango-net
    restart: unless-stopped

  # OTEL Collector
  otel-collector:
    profiles: [ "otel-collector" ]
    image: otel/opentelemetry-collector:0.135.0
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "14317:4317" # OTLP gRPC receiver (routes to both systems)
      - "14318:4318" # OTLP HTTP receiver (routes to both systems)
    networks:
      - otel-collector-net
      - signoz-net
      - jaeger-net


  # SigNoz Infrastructure Services
  signoz-init-clickhouse:
    !!merge <<: *signoz-common
    profiles: [ "signoz" ]
    image: clickhouse/clickhouse-server:25.5.6
    container_name: signoz-init-clickhouse
    command:
      - bash
      - -c
      - |
        version="v0.0.1"
        node_os=$$(uname -s | tr '[:upper:]' '[:lower:]')
        node_arch=$$(uname -m | sed s/aarch64/arm64/ | sed s/x86_64/amd64/)
        echo "Fetching histogram-binary for $${node_os}/$${node_arch}"
        cd /tmp
        wget -O histogram-quantile.tar.gz "https://github.com/SigNoz/signoz/releases/download/histogram-quantile%2F$${version}/histogram-quantile_$${node_os}_$${node_arch}.tar.gz"
        tar -xvzf histogram-quantile.tar.gz
        mv histogram-quantile /var/lib/clickhouse/user_scripts/histogramQuantile
    volumes:
      - ./signoz/clickhouse/user_scripts:/var/lib/clickhouse/user_scripts/
    networks:
      - signoz-net
    restart: on-failure

  signoz-zookeeper:
    !!merge <<: *signoz-zookeeper-defaults
    profiles: [ "signoz" ]
    container_name: signoz-zookeeper
    volumes:
      - signoz-zookeeper-db:/signoz/zookeeper
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_AUTOPURGE_INTERVAL=1
      - ZOO_ENABLE_PROMETHEUS_METRICS=yes
      - ZOO_PROMETHEUS_METRICS_PORT_NUMBER=9141
    networks:
      - signoz-net

  signoz-clickhouse:
    !!merge <<: *signoz-clickhouse-defaults
    profiles: [ "signoz" ]
    container_name: signoz-clickhouse
    volumes:
      - ./signoz/clickhouse/user_scripts:/var/lib/clickhouse/user_scripts/
      - ./signoz/clickhouse/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./signoz/clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./signoz/clickhouse/custom-function.xml:/etc/clickhouse-server/custom-function.xml
      - ./signoz/clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - signoz-clickhouse-db:/var/lib/clickhouse/
    networks:
      - signoz-net

  signoz-server:
    !!merge <<: *signoz-db-depend
    profiles: [ "signoz" ]
    image: signoz/signoz:v0.95.0
    container_name: signoz-server
    command:
      - --config=/root/config/prometheus.yml
    ports:
      - "3080:8080"
    volumes:
      - ./signoz/dashboards:/root/config/dashboards
      - ./signoz/signoz/prometheus.yml:/root/config/prometheus.yml
      - signoz-db:/var/lib/signoz/
    environment:
      - SIGNOZ_ALERTMANAGER_PROVIDER=signoz
      - SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN=tcp://signoz-clickhouse:9000
      - SIGNOZ_SQLSTORE_SQLITE_PATH=/var/lib/signoz/signoz.db
      - DASHBOARDS_PATH=/root/config/dashboards
      - STORAGE=clickhouse
      - GODEBUG=netdns=go
      - TELEMETRY_ENABLED=true
      - DEPLOYMENT_TYPE=docker-standalone-amd
      - DOT_METRICS_ENABLED=true
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - -q
        - localhost:8080/api/v1/health
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - signoz-net

  signoz-otel-collector:
    !!merge <<: *signoz-db-depend
    profiles: [ "signoz" ]
    image: signoz/signoz-otel-collector:v0.129.5
    container_name: signoz-otel-collector
    command:
      - --config=/etc/otel-collector-config.yaml
      - --manager-config=/etc/manager-config.yaml
      - --copy-path=/var/tmp/collector-config.yaml
      - --feature-gates=-pkg.translator.prometheus.NormalizeName
    volumes:
      - ./signoz/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./signoz/signoz/otel-collector-opamp-config.yaml:/etc/manager-config.yaml
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=host.name=signoz-host,os.type=linux
      - LOW_CARDINAL_EXCEPTION_GROUPING=false
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
    depends_on:
      signoz-server:
        condition: service_healthy
    networks:
      - signoz-net

  signoz-schema-migrator-sync:
    !!merge <<: *signoz-common
    profiles: [ "signoz" ]
    image: signoz/signoz-schema-migrator:v0.129.5
    container_name: signoz-schema-migrator-sync
    command:
      - sync
      - --dsn=tcp://signoz-clickhouse:9000
      - --up=
    depends_on:
      signoz-clickhouse:
        condition: service_healthy
    networks:
      - signoz-net
    restart: on-failure

  signoz-schema-migrator-async:
    !!merge <<: *signoz-db-depend
    profiles: [ "signoz" ]
    image: signoz/signoz-schema-migrator:v0.129.5
    container_name: signoz-schema-migrator-async
    command:
      - async
      - --dsn=tcp://signoz-clickhouse:9000
      - --up=
    networks:
      - signoz-net
    restart: on-failure

  # Jaeger
  jaeger:
    profiles: [ "jaeger" ]
    image: jaegertracing/all-in-one:1.73.0
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "24317:4317" # Direct OTLP gRPC (Jaeger only, no conflict)
      - "24318:4318" # Direct OTLP HTTP (Jaeger only, no conflict)
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_OTLP_HTTP_ENABLED=true
      - COLLECTOR_OTLP_GRPC_ENABLED=true
    networks:
      - jaeger-net
    restart: unless-stopped

networks:
  nango-net:
    driver: bridge
  otel-collector-net:
    driver: bridge
  jaeger-net:
    driver: bridge
  signoz-net:
    driver: bridge

volumes:
  nango-db:
  signoz-db:
  signoz-clickhouse-db:
  signoz-zookeeper-db:
