receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:  
  batch:
    send_batch_size: 1

exporters:
  # Export to SigNoz OTEL Collector
  otlp/signoz:
    endpoint: host.docker.internal:14317
    tls:
      insecure: true
  # Export to Jaeger
  otlp/jaeger:
    endpoint: host.docker.internal:24317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/signoz, otlp/jaeger]